# Generated by Django 3.0.5 on 2020-04-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('automobile', models.BooleanField()),
                ('bicycle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=20)),
                ('delivery_time_from', models.DateTimeField()),
                ('delivery_time_to', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('total_weight', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('breakable', models.BooleanField()),
                ('prepared', models.BooleanField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Courier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('breakable', models.BooleanField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_for', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('available', models.BooleanField()),
                ('status', models.CharField(default='nepripravený', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Store'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=1000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CIS.Customer')),
            ],
        ),
    ]
