# Generated by Django 3.0.5 on 2020-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIS', '0002_auto_20200413_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
