# Generated by Django 3.0.5 on 2020-04-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIS', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
