# Generated by Django 3.0.5 on 2020-04-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CIS', '0005_auto_20200413_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
