# Generated by Django 3.0.5 on 2020-04-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIS', '0010_auto_20200425_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='courier',
            new_name='courier_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='productsinorder',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='productsinorder',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productsinstore',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productsinstore',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='address_id',
        ),
    ]
