# Generated by Django 3.0.5 on 2020-04-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CIS', '0011_auto_20200426_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='courier_id',
            new_name='courier',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='productsinorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='productsinorder',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productsinstore',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productsinstore',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='address_id',
            new_name='address',
        ),
    ]
